#!/usr/bin/env bash
# Build-time config injection for the customer mini-program (task P1-1).
#
# Design trade-off: WeChat devtools import apps/miniprogram/ as the source
# directory, so a dist/ output would require duplicating the whole project
# tree. We instead overwrite utils/config.js + project.config.json appid in
# place and provide `--restore` to write the development defaults back.
# Tests point MP_TARGET_DIR at a scratch copy so the repo stays clean.
#
# Env:
#   MP_APP_ENV   development (default) | production
#   MP_API_BASE  API root URL (default: dev staging base)
#   MP_API_APPID (unused) — see MP_APPID
#   MP_APPID     WeChat AppID (default: touristappid)
#   MP_TARGET_DIR  override target dir (tests only)
#
# Fail-closed (MP_APP_ENV=production only — dev builds pass through):
#   - MP_APPID empty, touristappid, or not wx + 16 lowercase hex chars
#   - MP_API_BASE hits p.scolv.com, carries an explicit port, or is not https://
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_DIR="${MP_TARGET_DIR:-$ROOT_DIR/apps/miniprogram}"
CONFIG_JS="$TARGET_DIR/utils/config.js"
PROJECT_JSON="$TARGET_DIR/project.config.json"

# Development defaults — must stay byte-identical to the committed files.
DEV_APP_ENV='development'
DEV_API_BASE='https://p.scolv.com:8443'
DEV_APPID='touristappid'

fail() { printf 'release gate: %s\n' "$1" >&2; exit 1; }

set_appid() {
  # Regex-replace the appid value so the file formatting stays untouched.
  node -e '
    const fs = require("fs");
    const [file, appid] = process.argv.slice(1);
    const src = fs.readFileSync(file, "utf8");
    const out = src.replace(/("appid":\s*")[^"]*(")/, `$1${appid}$2`);
    if (out === src && !src.includes(`"appid": "${appid}"`)) {
      console.error("appid field not found in " + file);
      process.exit(1);
    }
    fs.writeFileSync(file, out);
  ' "$PROJECT_JSON" "$1"
}

write_config() {
  local app_env="$1" api_base="$2" header="$3"
  cat > "$CONFIG_JS" <<EOF
${header}
const APP_ENV = '${app_env}';
const API_BASE = '${api_base}';

function assertRuntimeConfig() {
  if (APP_ENV === 'production' && /(^|\.)p\.scolv\.com(?::|\/|\$)/.test(API_BASE)) {
    throw new Error('Production mini-program API_BASE must use the formal API host');
  }
}

module.exports = {
  APP_ENV,
  API_BASE,
  assertRuntimeConfig,
  // Scene keys: s=slug, h=hamster_id
};
EOF
}

if [ "${1:-}" = "--restore" ]; then
  write_config "$DEV_APP_ENV" "$DEV_API_BASE" \
'// Override in 微信开发者工具 local settings or CI inject for production.
// Production must set formal request合法域名 + real AppID (not touristappid).'
  set_appid "$DEV_APPID"
  printf 'restored development defaults in %s\n' "$TARGET_DIR"
  exit 0
fi

APP_ENV="${MP_APP_ENV:-$DEV_APP_ENV}"
API_BASE="${MP_API_BASE:-$DEV_API_BASE}"
APPID="${MP_APPID:-$DEV_APPID}"

if [ "$APP_ENV" = "production" ]; then
  test -n "$APPID" || fail 'MP_APPID is required for production builds'
  [ "$APPID" != "touristappid" ] || fail 'MP_APPID must not be touristappid for production builds'
  case "$APPID" in
    wx*) ;;
    *) fail "MP_APPID must start with wx for production builds, got $APPID" ;;
  esac
  [ "${#APPID}" -eq 18 ] || fail "MP_APPID must be wx + 16 hex chars (18 total), got ${#APPID} chars: $APPID"
  case "${APPID#wx}" in
    *[!0-9a-f]*) fail "MP_APPID must be wx followed by 16 lowercase hex chars, got $APPID" ;;
  esac
  case "$API_BASE" in
    https://*) ;;
    *) fail "MP_API_BASE must start with https://, got $API_BASE" ;;
  esac
  case "$API_BASE" in
    *p.scolv.com*) fail "MP_API_BASE hits staging host p.scolv.com: $API_BASE" ;;
  esac
  HOST_PART="${API_BASE#https://}"; HOST_PART="${HOST_PART%%/*}"
  case "$HOST_PART" in
    *:*) fail "MP_API_BASE must not carry an explicit port (WeChat requires default 443): $API_BASE" ;;
  esac
fi

# Guard the JS string interpolation below against broken output.
case "$API_BASE$APPID" in
  *"'"*|*'\'*) fail 'MP_API_BASE / MP_APPID must not contain quotes or backslashes' ;;
esac

write_config "$APP_ENV" "$API_BASE" \
'// Generated by scripts/build-miniprogram.sh — do not edit by hand.
// Run scripts/build-miniprogram.sh --restore to get development defaults back.'
set_appid "$APPID"
printf 'built mini-program config: APP_ENV=%s API_BASE=%s appid=%s\n' "$APP_ENV" "$API_BASE" "$APPID"
